@extends('layouts.app')

@php
    // The product in the order a person meets it. Every figure is a real capture
    // of this app (public/landing, regenerated by nexo-shots.mjs from a local
    // instance seeded with DemoSeeder) — never a redrawn screen.
    $steps = [
        ['shot' => 'shot-1', 'caption' => __('1 — Create your account')],
        ['shot' => 'shot-2', 'caption' => __('2 — Authorize your apps')],
        ['shot' => 'shot-3', 'caption' => __('3 — Control your active sessions')],
    ];

    // Every row is something the code enforces, and the source is named next to
    // it. A row with no real source does not exist (design.md, "Copy").
    $specs = [
        // config/nexo.php → password.min_length, read at runtime so the sheet
        // cannot drift from the rule the registration form applies.
        [__('Minimum password'), __(':min characters', ['min' => config('nexo.password.min_length')])],
        // config/auth.php → verification.expire (minutes).
        [__('Email verification link'), __('Expires after :minutes minutes', ['minutes' => config('auth.verification.expire')])],
        // App\Providers\AuthServiceProvider: tokensExpireIn / refreshTokensExpireIn.
        [__('SSO tokens'), __('Access 60 minutes · refresh 30 days')],
        // App\Http\Middleware\EnforcePkceS256 — a plain challenge is a 400.
        [__('PKCE'), __('S256 only — plain is rejected')],
        // App\Models\User uses HasUuids: the subject handed to every client is
        // that UUID, so changing your email never changes who you are.
        [__('Account identifier'), __('A stable UUID, never the email address')],
        // config/nexo.php → locales, plus the shared theme toggle.
        [__('Languages and themes'), __('es · en · pt — light and dark')],
    ];

    // The same answers the help center gives, in the same words — the landing
    // does not get a marketing rewrite of them.
    $faqs = array_slice((array) __('help.faqs'), 0, 4);
@endphp

@section('seo')
    <x-nexo-seo
        :title="config('app.name').' — '.__('One account for the whole Nexo ecosystem.')"
        :description="__('Sign in once and use every Nexo tool — open source, OpenID Connect.')"
        :canonical="url('/')" />
@endsection

@section('content')
    <section data-landing-section="hero">
        <h1 class="max-w-2xl text-4xl font-semibold tracking-tight text-ink sm:text-5xl">{{ __('One account for the whole Nexo ecosystem.') }}</h1>
        <p class="mt-5 max-w-xl text-lg text-muted">{{ __('Sign in once and use every Nexo tool — open source, OpenID Connect.') }}</p>
        <div class="mt-8 flex flex-wrap gap-3">
            @auth
                <a class="nexo-btn nexo-btn--primary" href="{{ url('/profile') }}">{{ __('Go to your account') }}</a>
            @else
                <a class="nexo-btn nexo-btn--primary" href="{{ url('/register') }}">{{ __('Create your account') }}</a>
                <a class="nexo-btn nexo-btn--ghost" href="{{ url('/login') }}">{{ __('Sign in') }}</a>
            @endauth
        </div>
    </section>

    <section data-landing-section="producto">
        <h2 class="text-2xl font-semibold tracking-tight text-ink">{{ __('How it works') }}</h2>

        <div class="mt-8 space-y-10 sm:mt-10 sm:space-y-12">
            @foreach ($steps as $step)
                <figure>
                    {{-- Four files per figure: theme × viewport. Both themes ship
                         because landing.css shows the one that matches
                         [data-theme]; both viewports ship because a 1280×800
                         capture shrunk to a phone is not the "legible without
                         zoom" STANDARD.md asks for. width/height are the real
                         pixels of each file, so nothing reflows on load. --}}
                    <img class="landing-shot landing-shot--desktop landing-shot--light w-full rounded-xl border border-line"
                         src="/landing/{{ $step['shot'] }}-light.webp"
                         width="1280" height="800" loading="lazy" decoding="async"
                         alt="{{ $step['caption'] }}">
                    <img class="landing-shot landing-shot--desktop landing-shot--dark w-full rounded-xl border border-line"
                         src="/landing/{{ $step['shot'] }}-dark.webp"
                         width="1280" height="800" loading="lazy" decoding="async"
                         alt="{{ $step['caption'] }}">
                    <img class="landing-shot landing-shot--mobile landing-shot--light w-full rounded-xl border border-line"
                         src="/landing/{{ $step['shot'] }}-mobile-light.webp"
                         width="390" height="844" loading="lazy" decoding="async"
                         alt="{{ $step['caption'] }}">
                    <img class="landing-shot landing-shot--mobile landing-shot--dark w-full rounded-xl border border-line"
                         src="/landing/{{ $step['shot'] }}-mobile-dark.webp"
                         width="390" height="844" loading="lazy" decoding="async"
                         alt="{{ $step['caption'] }}">
                    <figcaption class="mt-3 text-sm text-muted">{{ $step['caption'] }}</figcaption>
                </figure>
            @endforeach
        </div>
    </section>

    <section data-landing-section="datos">
        <h2 class="text-2xl font-semibold tracking-tight text-ink">{{ __('The numbers') }}</h2>
        <dl class="mt-6 border-t border-line">
            @foreach ($specs as [$term, $value])
                <div class="flex flex-col gap-1 border-b border-line py-3 sm:flex-row sm:gap-6 sm:py-4">
                    <dt class="text-sm font-medium text-ink sm:w-56 sm:shrink-0">{{ $term }}</dt>
                    <dd class="text-sm tabular-nums text-muted">{{ $value }}</dd>
                </div>
            @endforeach
        </dl>
    </section>

    <section data-landing-section="preguntas">
        <h2 class="text-2xl font-semibold tracking-tight text-ink">{{ __('Frequent questions') }}</h2>
        <div class="mt-6 border-t border-line">
            @foreach ($faqs as $faq)
                <details class="border-b border-line">
                    <summary class="flex min-h-11 cursor-pointer items-center text-sm font-medium text-ink">{{ $faq['q'] ?? '' }}</summary>
                    <div class="pb-4 text-sm text-muted">{!! $faq['a'] ?? '' !!}</div>
                </details>
            @endforeach
        </div>
        <p class="mt-4">
            {{-- inline-flex + min-h-11: a thumb needs 44px, and an inline link
                 is 18 (STANDARD.md, mobile-first). --}}
            <a href="{{ route('help') }}" class="inline-flex min-h-11 items-center text-sm font-medium text-primary hover:text-primary-hover hover:underline">{{ __('All questions') }}</a>
        </p>
    </section>

    <section data-landing-section="cierre">
        @auth
            <a class="nexo-btn nexo-btn--primary" href="{{ url('/profile') }}">{{ __('Go to your account') }}</a>
        @else
            <a class="nexo-btn nexo-btn--primary" href="{{ url('/register') }}">{{ __('Create your account') }}</a>
        @endauth
    </section>
@endsection
